version: '3'
services:
  odoo:
    image: odoo:16
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-addons:/mnt/extra-addons

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-addons:
  db-data:
